In [3]:
import numpy as np

In [4]:
a = np.arange(15).reshape(3, 5)

In [5]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
a.shape

(3, 5)

In [7]:
a.dtype.name

'int64'

In [8]:
 a.size

15

In [9]:
type(a)

numpy.ndarray

In [10]:
x  = np.array([6, 7, 8])

In [11]:
x

array([6, 7, 8])

In [10]:
a = np.arange(6)  

In [11]:
print(a)

[0 1 2 3 4 5]


In [12]:
b = np.arange(10)

In [13]:
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [14]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
a = np.array( [20,30,40,50, 90, 100, 200, 300] )

In [19]:
a

array([ 20,  30,  40,  50,  90, 100, 200, 300])

In [21]:
b = np.array([23])

In [22]:
b

array([23])

In [23]:
a - b

array([ -3,   7,  17,  27,  67,  77, 177, 277])

In [24]:
a * b

array([ 460,  690,  920, 1150, 2070, 2300, 4600, 6900])

In [25]:
a / b

array([ 0.86956522,  1.30434783,  1.73913043,  2.17391304,  3.91304348,
        4.34782609,  8.69565217, 13.04347826])